/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCampaignApplicationArgs } from "./CreateCampaignApplicationArgs";
import { UpdateCampaignApplicationArgs } from "./UpdateCampaignApplicationArgs";
import { DeleteCampaignApplicationArgs } from "./DeleteCampaignApplicationArgs";
import { CampaignApplicationFindManyArgs } from "./CampaignApplicationFindManyArgs";
import { CampaignApplicationFindUniqueArgs } from "./CampaignApplicationFindUniqueArgs";
import { CampaignApplication } from "./CampaignApplication";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { Campaign } from "../../campaign/base/Campaign";
import { CampaignApplicationService } from "../campaignApplication.service";

@graphql.Resolver(() => CampaignApplication)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CampaignApplicationResolverBase {
  constructor(
    protected readonly service: CampaignApplicationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "read",
    possession: "any",
  })
  async _campaignApplicationsMeta(
    @graphql.Args() args: CampaignApplicationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CampaignApplication])
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "read",
    possession: "any",
  })
  async campaignApplications(
    @graphql.Args() args: CampaignApplicationFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CampaignApplication[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CampaignApplication",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CampaignApplication, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "read",
    possession: "own",
  })
  async campaignApplication(
    @graphql.Args() args: CampaignApplicationFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CampaignApplication | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CampaignApplication",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CampaignApplication)
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "create",
    possession: "any",
  })
  async createCampaignApplication(
    @graphql.Args() args: CreateCampaignApplicationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CampaignApplication> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CampaignApplication",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CampaignApplication"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        campaign: args.data.campaign
          ? {
              connect: args.data.campaign,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CampaignApplication)
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "update",
    possession: "any",
  })
  async updateCampaignApplication(
    @graphql.Args() args: UpdateCampaignApplicationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CampaignApplication | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CampaignApplication",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CampaignApplication"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          campaign: args.data.campaign
            ? {
                connect: args.data.campaign,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CampaignApplication)
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "delete",
    possession: "any",
  })
  async deleteCampaignApplication(
    @graphql.Args() args: DeleteCampaignApplicationArgs
  ): Promise<CampaignApplication | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: CampaignApplication,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Campaign, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CampaignApplication",
    action: "read",
    possession: "any",
  })
  async campaign(
    @graphql.Parent() parent: CampaignApplication,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Campaign | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Campaign",
    });
    const result = await this.service.getCampaign(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
